//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVTFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdmin()
        {
            this.Materials = new HashSet<Material>();
        }
    
        public int Admin_ID { get; set; }
        public string Admin_Avatar { get; set; }
        public string Admin_Username { get; set; }
        public string Admin_Email { get; set; }
        public string Admin_Phone { get; set; }
        public string Admin_NickYahoo { get; set; }
        public string Admin_NickSkype { get; set; }
        public int Roles_ID { get; set; }
        public Nullable<System.DateTime> Admin_Created { get; set; }
        public Nullable<System.DateTime> Admin_Log { get; set; }
        public bool Admin_LoginType { get; set; }
        public bool Admin_Sex { get; set; }
        public Nullable<System.DateTime> Admin_Birth { get; set; }
        public string Admin_Address { get; set; }
        public string Admin_Permission { get; set; }
        public string Admin_FullName { get; set; }
        public bool Admin_Actived { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Materials { get; set; }
    }
}
